version: "3.2"
services:
  workflows_deployer:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - GCP_REGION
      - GCP_PROJECT
      - API_KEY
    volumes:
      - ${PWD}:/app
      - ${HOME}/.google-credentials:/.google-credentials
      #- ${HOME}/scentregroup/workflows-deployer-dkimg/workflows-test.json:/.google-credentials
