env:
  GCP_REGION: asia-southeast1

steps:
  - name: ":rocket: deploy to dev"
    env:
      GCP_PROJECT: scg-hip-dev
      VAULT_ENVS: "API_KEY:secret/gcp/scg-hip-dev/secrets/hris/PSOFT_API_PASSWORD"
    plugins:
      - docker-compose#v3.3.0:
          run: workflows_deployer
          shell: false
          config:
            - docker-compose.yml
    branches: "feat* develop main"
    concurrency: 1
    concurrency_group: "${ENV}-${BUILDKITE_PIPELINE_SLUG}"

  - name: ":docker: Tag and Push image to GCR"
    env:
      GCP_PROJECT: scg-hip-dev
      VAULT_ENVS: "API_KEY:secret/gcp/scg-hip-dev/secrets/hris/PSOFT_API_PASSWORD"
    command: ./push.sh
    plugins:
      - docker-compose#v3.3.0:
          run: workflows_deployer
          shell: false
          config:
            - docker-compose.yml
    branches: "feat* develop main"
    concurrency: 1
    concurrency_group: "${ENV}-${BUILDKITE_PIPELINE_SLUG}"